// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCON4hQ9tv6lnkyfr9fecULCDaUhdNiCs0',
    appId: '1:579065873976:web:a55a988a3bfd7c693e88cd',
    messagingSenderId: '579065873976',
    projectId: 'messaging-app-dc303',
    authDomain: 'messaging-app-dc303.firebaseapp.com',
    storageBucket: 'messaging-app-dc303.firebasestorage.app',
    measurementId: 'G-1DZ3T6F0M3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_31VwyCqTYpi-hL4ChDZ2dKpMWH9svNE',
    appId: '1:579065873976:android:10f4e9523c1fbe113e88cd',
    messagingSenderId: '579065873976',
    projectId: 'messaging-app-dc303',
    storageBucket: 'messaging-app-dc303.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1cpPRqtKNx7eMRCjNSje8DmlLcpBWQDs',
    appId: '1:579065873976:ios:3590a8f53d7f3aac3e88cd',
    messagingSenderId: '579065873976',
    projectId: 'messaging-app-dc303',
    storageBucket: 'messaging-app-dc303.firebasestorage.app',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1cpPRqtKNx7eMRCjNSje8DmlLcpBWQDs',
    appId: '1:579065873976:ios:3590a8f53d7f3aac3e88cd',
    messagingSenderId: '579065873976',
    projectId: 'messaging-app-dc303',
    storageBucket: 'messaging-app-dc303.firebasestorage.app',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCON4hQ9tv6lnkyfr9fecULCDaUhdNiCs0',
    appId: '1:579065873976:web:240db6666fca6f1f3e88cd',
    messagingSenderId: '579065873976',
    projectId: 'messaging-app-dc303',
    authDomain: 'messaging-app-dc303.firebaseapp.com',
    storageBucket: 'messaging-app-dc303.firebasestorage.app',
    measurementId: 'G-5SSP23ECHJ',
  );
}
